name: turkish_mangala
description: "A traditional Turkish Mangala game in Flutter."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/masa.png
    - lib/assets/tas.png
    - lib/assets/masa.svg
    - lib/assets/tas.svg